name: Build

on:
  push:
    tags-ignore:
      - '*'
    branches: 
      - '**'
jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Create next version
      id: new_tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        DEFAULT_BUMP: patch

    - name: Version
      run: npm ${{ steps.new_tag.outputs.part }}

    - name: Publish
      run: npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.new_tag.outputs.new_tag }}