name: Build

on:
  push:
    tags-ignore:
      - '*'
    branches: 
      - '**'

env:
  PACKAGE_NAME: '@oysteinvesth/gh-actions-workflows'

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      tag: steps.new_tag.outputs.new_tag
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Create next version
      id: new_tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        DEFAULT_BUMP: patch
        
    - name: Push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        CUSTOM_TAG: ${{ steps.new_tag.outputs.new_tag }}

    - name: Version
      run: |
        git config --global user.name "Test"
        git config --global user.email "test@gmail.com"
        npm --no-git-tag-version version from-git

    - name: Publish
      run: npm publish --tag beta
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .


  beta:
    needs: build

  prod:
    needs: beta
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Promote
      run: |
        npm dist-tag add ${{ env.PACKAGE_NAME }}@$(echo ${{ needs.build.outputs.tag }} | sed -e s/v//) latest
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}