name: Release

on:
  workflow_run: 
    workflows: ['Build']
    types: [ completed ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:        
      - name: Release
        uses: oysteinvesth/gh-actions-workflows/first@1
        
