name: SemVer Title Checker

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest
    steps:

    - uses: actions/github-script@v6
      name: Check title
      with:
        script: |
          const title = context.payload.pull_request.title
          const semverTags = [ '#patch', '#minor', '#major', '#none' ]
          if (!semverTags.some(tag => title.endsWith(tag))) {
            core.setFailed(`PR title must end with one of the following semver tags: ${semverTags.join(', ')}`)
          }
          