name: Comment PR

on:
  pull_request:
    types: [opened]

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      env:
        RELEASE_CHANNEL_BASE_URI: 'https://testing.com'
        TFSO_MODULE: 'product'
      with:
        script: |
          const { RELEASE_CHANNEL_BASE_URI, TFSO_MODULE } = process.env
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Remember to test the site! 👉 ${RELEASE_CHANNEL_BASE_URI}/modules/${TFSO_MODULE}`
          })